describe('inputa bir metin giren test', () => {
  it('hatalı metin girişi yapılınca hata mesajı gösterilmeli', () => {
    cy.viewport(1920, 1080)
    cy.visit('http://localhost:5173/')
    cy.get(`#aciktim-button`).click()
    cy.get(`input[name="isim"]`).type('ab')
    cy.get(`#isim-hata`).should('be.visible')
  })
  it('birden fazla malzeme seçilebilmeli', () => {
    cy.viewport(1920, 1080)
    cy.visit('http://localhost:5173/')
    cy.get(`#aciktim-button`).click()
    cy.get('input[value="Ananas"]').check()
    cy.get('input[value="Mısır"]').check()
    cy.get('input[value="Sucuk"]').check()
    cy.get('input[value="Salam"]').check()
  })
  it('ilgili kısımlar doldurulduktan sonra form başarılır bir şekilde gönderilebilmeli', () => {
    cy.viewport(1920, 1080)
    cy.visit('http://localhost:5173/')
    cy.get(`#aciktim-button`).click()
    cy.get('input[value="orta"]').check()
    cy.get('select[name="hamur"]').select('ince') 
    cy.get('input[value="Ananas"]').check()
    cy.get('input[value="Mısır"]').check()
    cy.get('input[value="Sucuk"]').check()
    cy.get('input[value="Salam"]').check()
     cy.get(`input[name="isim"]`).type('ali')
     cy.get(`#siparis-ver-butonu`).click()
  })
})